#!/usr/bin/env python3
import os
import subprocess

HEADER = """
[Script Info]
; Script generated by Aegisub 3.2.2
; http://www.aegisub.org/
Title: Default Aegisub file
ScriptType: v4.00+
WrapStyle: 0
ScaledBorderAndShadow: yes
YCbCr Matrix: TV.601
PlayResX: 1920
PlayResY: 1080

[V4+ Styles]
Format: Name, Fontname, Fontsize, PrimaryColour, SecondaryColour, OutlineColour, BackColour, Bold, Italic, Underline, StrikeOut, ScaleX, ScaleY, Spacing, Angle, BorderStyle, Outline, Shadow, Alignment, MarginL, MarginR, MarginV, Encoding
Style: Default,Arial,68,&H00FFFFFF,&H000000FF,&H00000000,&H00000000,0,0,0,0,100,100,0,0,1,2.25,2.25,2,30,30,45,1

[Events]
Format: Layer, Start, End, Style, Name, MarginL, MarginR, MarginV, Effect, Text
""".lstrip()
inputs = [i for i in os.listdir('.') if i.endswith('.in')]

for i in inputs:
    lines = list(open(i))
    num_files = int(lines[0])
    idx = 1
    groups = []
    for _ in range(num_files):
        num_lines = int(lines[idx])
        next_idx = idx + 1 + num_lines
        group = []
        for line in lines[idx+1:next_idx]:
            s, e = line.split()
            group.append((int(s), int(e)))
        groups.append(group)
        idx = next_idx
    assert idx == len(lines)
    for gi, group in enumerate(groups):
        with open(i.replace('.in', str(gi) + '.ass'), 'w') as f:
            print(HEADER, file=f)
            for li, (s, e) in enumerate(group):
                print('Dialogue: 0,0:{}:{}.00,0:{}:{}.00,Default,,0,0,0,,start{},end{},line{}'
                          .format(s // 60, s % 60, e // 60, e % 60, s, e, li), file=f)
